# -*- coding: utf-8 -*-
"""生成最终的电磁学复习提纲 — 基于全部课件+例题+习题"""

content = ""

def w(text):
    global content
    content += text + "\n"

# ====== 封面 ======
w("# 电磁学 期末考试复习提纲")
w("")
w("**杨思辰  PB25992094  未来技术学院  物理学专业**")
w("")
w("教材：胡友秋等《电磁学》（科学出版社，2024）")
w("")
w("> **使用说明**：本提纲基于全部课程课件（EM000–EM010）、教材例题和课后习题整理。")
w("> 标注 ★ 为核心考点，标注 ▲ 为高频考题类型，标注 ※ 为易错点。")
w("")

# ====== 考试信息 ======
w("\\newpage")
w("# 考试概况与应试策略")
w("")
w("## 考试题型预测")
w("")
w("| 题型 | 分值占比 | 来源 | 策略 |")
w("|------|---------|------|------|")
w("| 选择/填空题 | ~20% | 基本概念和公式 | 熟记核心公式，注意单位 |")
w("| 简答题 | ~15% | 物理图像+定理表述 | 麦克斯韦方程组必考 |")
w("| 计算题 | ~50% | 课后习题+例题变体 | 对称性+高斯/安培环路定理 |")
w("| 证明/推导题 | ~15% | 能量守恒、波动方程等 | 注意逻辑完整性 |")
w("")
w("## 通用应试技巧")
w("")
w("1. **对称性是解题第一原则**：拿到题目先分析对称性（球/柱/面对称），对称性足够→直接用高斯定理或安培环路定理，避免复杂积分。")
w("2. **边界条件是分区介质的关键**：$D_n$ 连续（无自由面电荷时）、$E_t$ 连续；$B_n$ 连续、$H_t$ 连续（无面自由电流时）。")
w("3. **能量法求力/求L/C**：$F=-\\partial W/\\partial x$（注意 $Q$ 不变还是 $U$ 不变用不同符号）。$L=2W_m/I^2$ 求自感比磁通法更普适。")
w("4. **复数法解交流电路**：$Z_L=j\\omega L$，$Z_C=1/(j\\omega C)$，串联分压/并联分流与直流电阻规则完全一致。")
w("5. **单位与量纲检查**：最终结果用 $\\varepsilon_0,\\mu_0$ 表示并检查量纲是否正确。常见陷阱：$1/(4\\pi\\varepsilon_0)$ 和 $\\mu_0/(4\\pi)$ 的混淆。")
w("6. **考前重点复习**：高斯定理应用(★)、安培环路定理(★)、法拉第电磁感应定律(★)、RLC暂态(▲)、麦克斯韦方程组(★必考)")
w("")

# ====== 第一章 ======
w("\\newpage")
w("# 第一章  真空中的静电场  ★★★")
w("")
w("> **对应课件**：EM001A–D（共228页）| **教材**：第1章 | **课时比重**：约15%")
w("")
w("## 核心考点")
w("")
w("### ★1. 库仑定律与叠加原理")
w("$$\\boldsymbol{F}_{12} = \\frac{1}{4\\pi\\varepsilon_0}\\frac{q_1 q_2}{r^2}\\hat{\\boldsymbol{r}}_{12}$$")
w("叠加原理是电磁学的**第一性原理**：$\\boldsymbol{E}(\\boldsymbol{r}) = \\frac{1}{4\\pi\\varepsilon_0}\\sum_i \\frac{q_i(\\boldsymbol{r}-\\boldsymbol{r}_i)}{|\\boldsymbol{r}-\\boldsymbol{r}_i|^3}$")
w("")
w("### ★★2. 高斯定理（计算题核心工具）")
w("$$\\oint_S \\boldsymbol{E}\\cdot d\\boldsymbol{S} = \\frac{Q_{\\text{enc}}}{\\varepsilon_0}$$")
w("")
w("**使用条件**：电荷分布具有球对称/柱对称/面对称，且高斯面选择恰当。")
w("")
w("| 带电体 | 高斯面 | $E$ 大小 | 方向 |")
w("|--------|--------|---------|------|")
w("| 点电荷/均匀带电球(外) | 同心球面 | $Q/(4\\pi\\varepsilon_0 r^2)$ | 径向 |")
w("| 无限长均匀带电直线/圆柱(外) | 同轴圆柱面 | $\\lambda/(2\\pi\\varepsilon_0 r)$ | 径向 |")
w("| 无限大均匀带电平面 | 柱形高斯面 | $\\sigma/(2\\varepsilon_0)$ | 垂直板面 |")
w("| 均匀带电球体(内) | 同心球面 | $Qr/(4\\pi\\varepsilon_0 R^3)$ | 径向 |")
w("")
w("※ **易错**：均匀带电球面内部 $E=0$，但均匀带电球体内部 $E\\neq 0$。")
w("")
w("### ★3. 环路定理与电势")
w("$$\\oint_L \\boldsymbol{E}\\cdot d\\boldsymbol{l} = 0 \\quad\\Leftrightarrow\\quad \\nabla\\times\\boldsymbol{E}=0$$")
w("$$\\varphi(\\boldsymbol{r}) = \\int_{\\boldsymbol{r}}^{\\infty}\\boldsymbol{E}\\cdot d\\boldsymbol{l}, \\quad \\boldsymbol{E} = -\\nabla\\varphi$$")
w("**重要性**：电势为标量，先求 $\\varphi$ 再求 $\\boldsymbol{E}$ 往往比直接矢量积分简单。")
w("")
w("### ▲4. 电偶极子（高频考题）")
w("$$\\varphi = \\frac{\\boldsymbol{p}\\cdot\\hat{\\boldsymbol{r}}}{4\\pi\\varepsilon_0 r^2}, \\quad \\boldsymbol{E} = \\frac{3(\\boldsymbol{p}\\cdot\\hat{\\boldsymbol{r}})\\hat{\\boldsymbol{r}}-\\boldsymbol{p}}{4\\pi\\varepsilon_0 r^3}$$")
w("轴线上：$E = 2p/(4\\pi\\varepsilon_0 r^3)$；中垂面上：$E = p/(4\\pi\\varepsilon_0 r^3)$。")
w("在均匀外场 $\\boldsymbol{E}_0$ 中所受**力矩** $\\boldsymbol{\\tau} = \\boldsymbol{p}\\times\\boldsymbol{E}_0$；**势能** $W = -\\boldsymbol{p}\\cdot\\boldsymbol{E}_0$。")
w("")
w("## ▲ 自测习题（5题）")
w("")
w("**T1-1**（高斯定理）：半径为 $R$ 的无限长均匀带电圆柱体，体电荷密度 $\\rho$，求柱内外电场分布。")
w("")
w("**T1-2**（叠加法）：一均匀带电半圆环（半径 $R$，线密度 $\\lambda$），求圆心处电场。")
w("")
w("**T1-3**（电势法）：求均匀带电圆盘轴线上任意点的电势和电场。")
w("")
w("**T1-4**（补偿法）：均匀带电球体（半径 $R$，密度 $\\rho$）内有一球形空腔，证明空腔内为匀强电场。")
w("")
w("**T1-5**（电偶极子）：求电偶极子在点电荷 $Q$ 的电场中所受的力和力矩。")
w("")

# ====== 第二章 ======
w("\\newpage")
w("# 第二章  静电场中的导体和电介质  ★★★")
w("")
w("> **对应课件**：EM002A–D（共372页）| **教材**：第2章 | **课时比重**：约20%（最大章）")
w("")
w("## 核心考点")
w("")
w("### ★★1. 静电场中的导体")
w("静电平衡条件：导体内 $\\boldsymbol{E}=0$ → 导体为等势体；电荷只分布在表面；$E_{\\text{表面}} = \\sigma/\\varepsilon_0$（垂直表面）。")
w("**尖端放电**：曲率半径小处 $\\sigma$ 大、$E$ 大。**静电屏蔽**：接地导体壳内外的电场互不影响。")
w("")
w("### ★★2. 电容与电容器")
w("$$C = \\frac{Q}{U}$$")
w("| 电容器类型 | 电容公式 | 注意 |")
w("|-----------|---------|------|")
w("| 平行板 | $C = \\varepsilon_0 S/d$ | 忽略边缘效应 |")
w("| 球形 | $C = 4\\pi\\varepsilon_0\\frac{ab}{b-a}$ | $a<b$ 为内外半径 |")
w("| 圆柱形 | $C = \\frac{2\\pi\\varepsilon_0 l}{\\ln(b/a)}$ | 单位长度 |")
w("| 孤立导体球 | $C = 4\\pi\\varepsilon_0 R$ | 外球壳 $b\\to\\infty$ |")
w("")
w("串联：$1/C = 1/C_1 + 1/C_2$（电压分压）；并联：$C = C_1 + C_2$（电荷分担）。")
w("")
w("### ★★★3. 电介质的极化与 $\\boldsymbol{D}$ 矢量（必考）")
w("")
w("**极化强度** $\\boldsymbol{P}$：单位体积内的电偶极矩。")
w("**极化电荷**：$\\rho' = -\\nabla\\cdot\\boldsymbol{P}$（体），$\\sigma' = \\boldsymbol{P}\\cdot\\hat{\\boldsymbol{n}}$（面）。")
w("**电位移矢量**：")
w("$$\\boldsymbol{D} = \\varepsilon_0\\boldsymbol{E} + \\boldsymbol{P}$$")
w("$$\\oint_S \\boldsymbol{D}\\cdot d\\boldsymbol{S} = Q_f \\quad\\text{（仅与自由电荷有关！）}$$")
w("")
w("各向同性线性介质本构关系：")
w("$$\\boldsymbol{P} = \\chi_e\\varepsilon_0\\boldsymbol{E}, \\quad \\boldsymbol{D} = \\varepsilon_0\\varepsilon_r\\boldsymbol{E}, \\quad \\varepsilon_r = 1+\\chi_e$$")
w("")
w("### ★★4. 边界条件（分区介质的核心工具）")
w("$$D_{1n} - D_{2n} = \\sigma_f \\quad \\text{（无自由面电荷时 } D_n \\text{ 连续）}$$")
w("$$E_{1t} = E_{2t} \\quad \\text{（切向 } E \\text{ 始终连续）}$$")
w("$$\\frac{\\tan\\theta_1}{\\tan\\theta_2} = \\frac{\\varepsilon_1}{\\varepsilon_2} \\quad \\text{（$D$ 线折射定律）}$$")
w("")
w("### ★5. 唯一性定理与镜像法")
w("**唯一性定理**：给定导体电荷或电势+边界条件，解唯一→可以\"猜\"解。")
w("**平面镜像法**：接地导体平面 → 等效用异号镜像电荷替代。")
w("**球面镜像法**：接地导体球 → 镜像电荷 $q' = -\\frac{R}{d}q$，位置 $r' = R^2/d$。")
w("")
w("※ **易错**：镜像电荷是**等效**的数学工具，不能用于计算镜像区域内的场。")
w("")
w("## ▲ 自测习题（6题）")
w("")
w("**T2-1**（电容计算）：平行板电容器中插入厚 $t$、$\\varepsilon_r$ 的介质板，求电容变化。两种极限：介质充满 vs. 介质紧贴一极板。")
w("")
w("**T2-2**（$\\boldsymbol{D}$ 矢量应用）：球形电容器内充满两种同心分层介质（分界面半径 $d$），求电容和各界面电荷。")
w("")
w("**T2-3**（边界条件）：平行板电容器两极板间有两层介质（$\\varepsilon_1,\\varepsilon_2$），厚度分别为 $d_1,d_2$，极板电压 $U$。求各介质中的 $E$ 和 $D$。")
w("")
w("**T2-4**（镜像法—平面）：点电荷 $q$ 距接地导体平面 $d$。求表面的感应电荷分布和总感应电荷。")
w("")
w("**T2-5**（镜像法—球面）：点电荷 $q$ 距接地导体球（半径 $R$）球心 $d$。求镜像电荷的大小和位置，以及点电荷所受的力。")
w("")
w("**T2-6**（综合）：导体球外有同心介质球壳，导体带电荷 $Q$。求 $\\boldsymbol{D},\\boldsymbol{E},\\boldsymbol{P}$ 分布、极化电荷、电容。")
w("")

# ====== 第三章 ======
w("\\newpage")
w("# 第三章  静电能  ★★")
w("")
w("> **对应课件**：EM003A–B（共102页）| **教材**：第3章 | **课时比重**：约8%")
w("")
w("## 核心考点")
w("")
w("### ★1. 静电能的多种表达式")
w("$$W_e = \\frac{1}{2}\\sum_i q_i\\varphi_i = \\frac{1}{2}\\int\\rho\\varphi\\,dV = \\frac{1}{2}\\int\\sigma\\varphi\\,dS$$")
w("$$W_e = \\frac{1}{2}QU = \\frac{1}{2}CU^2 = \\frac{Q^2}{2C} \\quad \\text{（电容器）}$$")
w("")
w("### ★★2. 电场能量密度（场的观点是重点！）")
w("$$w_e = \\frac{1}{2}\\boldsymbol{D}\\cdot\\boldsymbol{E} = \\frac{1}{2}\\varepsilon_0\\varepsilon_r E^2$$")
w("$$W_e = \\int_V w_e\\,dV$$")
w("**场的观点**：能量存储在电场中，而不是在电荷上。这是电磁场理论的基石。")
w("")
w("### ★3. 虚功原理求静电力（▲高频考点）")
w("")
w("| 条件 | 公式 | 适用场景 |")
w("|------|------|---------|")
w("| 电荷不变 $Q$=const | $F_x = -\\left.\\frac{\\partial W}{\\partial x}\\right|_Q$ | 孤立带电体 |")
w("| 电压不变 $U$=const | $F_x = +\\left.\\frac{\\partial W}{\\partial x}\\right|_U$ | 接电源 |")
w("")
w("※ **易错**：两种条件下电容器的力大小相同（$F=Q^2/(2C^2)\\cdot dC/dx$），但能量分析中电源是否做功不同。")
w("")
w("## ▲ 自测习题（4题）")
w("")
w("**T3-1**：均匀带电球面（半径 $R$，电荷 $Q$）的静电自能。由 $W=e^2/(8\\pi\\varepsilon_0 R)$ 估算电子\"经典半径\"。")
w("")
w("**T3-2**：平行板电容器接电源（电压 $U$），极板间距从 $d_1$ 拉到 $d_2$。求：(1)电场力做的功；(2)电源提供的能量；(3)电场能量的变化。三者关系如何？")
w("")
w("**T3-3**：用虚功原理求平行板电容器两极板间的吸引力（分别用 $Q$=const 和 $U$=const）。")
w("")
w("**T3-4**：一半介质半真空的平行板电容器（$\\varepsilon_r$ 的介质板可沿板面方向拉出）。求将介质板拉入电容器所需的力。")
w("")

# ====== 第四章 ======
w("\\newpage")
w("# 第四章  稳恒电流  ★")
w("")
w("> **对应课件**：EM004A–B（共151页）| **教材**：第4章 | **课时比重**：约7%")
w("")
w("## 核心考点")
w("")
w("### ★1. 电流密度与连续方程")
w("$$\\boldsymbol{j} = nq\\boldsymbol{v}_d, \\quad I = \\int_S \\boldsymbol{j}\\cdot d\\boldsymbol{S}$$")
w("$$\\nabla\\cdot\\boldsymbol{j} + \\frac{\\partial\\rho}{\\partial t} = 0 \\quad \\text{（电荷守恒）}$$")
w("稳恒条件：$\\nabla\\cdot\\boldsymbol{j}=0$——基尔霍夫第一定律的微分基础。")
w("")
w("### ★2. 欧姆定律与电阻计算")
w("微分形式：$\\boldsymbol{j} = \\sigma\\boldsymbol{E}$。积分形式：$U = IR$。")
w("$$R = \\int \\frac{dl}{\\sigma S} \\quad \\text{（非均匀截面）}$$")
w("※ 常见考题：球壳间、同轴圆筒间填充电导率 $\\sigma$ 的介质，求电阻。关键在于用对称性求 $\\boldsymbol{j}=I/(\\text{面积})$，再积分 $E=j/\\sigma$，得 $U$。")
w("")
w("### ★3. 基尔霍夫定律")
w("**KCL（节点）**：$\\sum I_{\\text{in}} = \\sum I_{\\text{out}}$")
w("**KVL（回路）**：$\\sum\\mathcal{E} = \\sum IR$（沿回路绕行，电压升=电压降）")
w("")
w("### 4. 弛豫时间")
w("$$\\tau = \\frac{\\varepsilon}{\\sigma}$$")
w("体电荷在导体内指数衰减。铜：$\\tau\\approx 10^{-19}\\,\\text{s}$——极短！这就是为何稳恒电流中导体内部 $\\rho=0$。")
w("")
w("## ▲ 自测习题（3题）")
w("")
w("**T4-1**（电阻计算）：同轴电缆内外导体半径 $a,b$，中间填充电导率 $\\sigma$ 的介质。求单位长度的漏电阻。")
w("")
w("**T4-2**（基尔霍夫）：含两个电源和三个电阻的电路，用支路电流法或回路电流法求各支路电流。")
w("")
w("**T4-3**（综合—$RC$ 类比）：证明 $RC = \\varepsilon/\\sigma$，并解释其物理意义（时间量纲）。")
w("")

# ====== 第五章 ======
w("\\newpage")
w("# 第五章  真空中的静磁场  ★★★")
w("")
w("> **对应课件**：EM005A–D（共299页）| **教材**：第5章 | **课时比重**：约15%")
w("")
w("## 核心考点")
w("")
w("### ★1. 洛伦兹力")
w("$$\\boldsymbol{F} = q(\\boldsymbol{E} + \\boldsymbol{v}\\times\\boldsymbol{B})$$")
w("带电粒子在均匀磁场中做螺旋运动：回旋频率 $\\omega_c = |q|B/m$，半径 $r=mv_\\perp/(|q|B)$。")
w("**霍尔效应**：$U_H = \\frac{IB}{nqd}$（横向电压，符号判载流子类型）。")
w("")
w("### ★★2. 毕奥-萨伐尔定律")
w("$$d\\boldsymbol{B} = \\frac{\\mu_0}{4\\pi}\\frac{I d\\boldsymbol{l}\\times\\hat{\\boldsymbol{r}}}{r^2}$$")
w("**必须记住的磁场公式**：")
w("| 电流分布 | $B$ | 方向 |")
w("|---------|-----|------|")
w("| 无限长直导线 | $\\mu_0 I/(2\\pi r)$ | 右手定则(环向) |")
w("| 圆环中心 | $\\mu_0 I/(2R)$ | 轴向 |")
w("| 圆环轴线上 | $\\mu_0 I R^2/[2(R^2+z^2)^{3/2}]$ | 轴向 |")
w("| 有限长直导线 | $\\mu_0 I(\\cos\\theta_1-\\cos\\theta_2)/(4\\pi r)$ | 环向 |")
w("| 长直螺线管内 | $\\mu_0 nI$ | 轴向 |")
w("| 螺绕环内 | $\\mu_0 NI/(2\\pi r)$ | 环向 |")
w("")
w("### ★★★3. 安培环路定理（必考，与高斯定理对称！）")
w("$$\\oint_L \\boldsymbol{B}\\cdot d\\boldsymbol{l} = \\mu_0 I_{\\text{enc}}$$")
w("$$\\nabla\\times\\boldsymbol{B} = \\mu_0\\boldsymbol{j}$$")
w("**适用条件**：电流分布具有对称性→磁场方向已知、大小仅依赖于一个坐标。")
w("")
w("### 4. 磁场高斯定理（与静电场高斯定理对比）")
w("$$\\oint_S \\boldsymbol{B}\\cdot d\\boldsymbol{S} = 0 \\;\\Leftrightarrow\\; \\nabla\\cdot\\boldsymbol{B}=0$$")
w("**无磁荷（磁单极子不存在）** — 这是电场和磁场的根本区别！")
w("")
w("### 5. 安培力")
w("$$d\\boldsymbol{F} = I d\\boldsymbol{l}\\times\\boldsymbol{B}$$")
w("两平行载流导线间单位长力：$f = \\mu_0 I_1 I_2/(2\\pi d)$（同向相吸、反向相斥）。")
w("")
w("## ▲ 自测习题（6题）")
w("")
w("**T5-1**（毕-萨定律）：正方形载流线圈（边长 $a$，电流 $I$）中心处的 $B$。推广到正 $n$ 边形。")
w("")
w("**T5-2**（安培环路定理）：无限长圆柱导体（半径 $a$）电流均匀分布，求柱内外 $B$。若电流只分布表面，结果如何？")
w("")
w("**T5-3**（叠加原理）：亥姆霍兹线圈——两同轴圆线圈（半径 $R$、间距 $R$、同向电流 $I$），证明中心附近 $B$ 最均匀。")
w("")
w("**T5-4**（洛伦兹力）：带电粒子以 $\\boldsymbol{v}_0$ 斜射入均匀 $\\boldsymbol{B}$（夹角 $\\theta$），求螺旋运动的半径、螺距和回旋频率。")
w("")
w("**T5-5**（磁约束—绝热不变量）：磁场缓慢变化时，粒子轨道磁矩 $\\mu=mv_\\perp^2/(2B)$ 守恒。由此解释磁镜中粒子的约束和逃逸。")
w("")
w("**T5-6**（综合）：一宽为 $2a$ 的无限长薄板载有均匀面电流，求空间中 $B$ 的分布。")
w("")

# ====== 第六章 ======
w("\\newpage")
w("# 第六章  静磁场中的磁介质  ★★")
w("")
w("> **对应课件**：EM006A–B（共152页）| **教材**：第6章 | **课时比重**：约8%")
w("")
w("## 核心考点")
w("")
w("### ★1. 磁化强度 $\\boldsymbol{M}$ 与磁化电流")
w("$$\\boldsymbol{j}' = \\nabla\\times\\boldsymbol{M} \\quad \\text{（体磁化电流）}$$")
w("$$\\boldsymbol{i}' = \\boldsymbol{M}\\times\\hat{\\boldsymbol{n}} \\quad \\text{（面磁化电流）}$$")
w("")
w("### ★★★2. 磁场强度 $\\boldsymbol{H}$ 与安培环路定理（必考！）")
w("$$\\boldsymbol{H} = \\frac{\\boldsymbol{B}}{\\mu_0} - \\boldsymbol{M}$$")
w("$$\\oint_L \\boldsymbol{H}\\cdot d\\boldsymbol{l} = I_f \\quad \\text{（仅与自由电流有关！）}$$")
w("")
w("各向同性线性磁介质：$\\boldsymbol{M} = \\chi_m\\boldsymbol{H}$，$\\boldsymbol{B} = \\mu_0(1+\\chi_m)\\boldsymbol{H} = \\mu_0\\mu_r\\boldsymbol{H}$。")
w("")
w("| 介质类型 | $\\mu_r$ | $\\chi_m$ | 举例 |")
w("|---------|---------|----------|------|")
w("| 抗磁质 | $<1$（略小） | $<0$（$\\sim -10^{-5}$） | 水、铜、铋 |")
w("| 顺磁质 | $>1$（略大） | $>0$（$\\sim 10^{-4}$） | 铝、铂、氧 |")
w("| 铁磁质 | $\\gg 1$（$10^3-10^5$） | $\\gg 0$（非线性） | 铁、钴、镍 |")
w("")
w("### ★3. 边界条件")
w("$$B_{1n} = B_{2n} \\quad \\text{（$B$ 法向连续，无磁荷）}$$")
w("$$H_{1t} - H_{2t} = i_f \\quad \\text{（$H$ 切向差=面自由电流）}$$")
w("")
w("### ▲4. 磁路定理（工程应用，高频考题）")
w("类比电路：磁动势 $\\mathcal{F}=NI$ ↔ 电动势；磁阻 $\\mathcal{R}=l/(\\mu S)$ ↔ 电阻；磁通 $\\Phi$ ↔ 电流。")
w("含气隙磁路：总磁阻 $\\mathcal{R}_{\\text{tot}} = \\mathcal{R}_{\\text{core}}+\\mathcal{R}_{\\text{gap}}$。气隙虽小，磁阻极大（$\\mu_0\\ll\\mu$）。")
w("")
w("## ▲ 自测习题（4题）")
w("")
w("**T6-1**：无限长直导线（半径 $a$，电流 $I$ 均匀分布）外包磁导率 $\\mu$ 的介质（外半径 $b$）。求 $H,B$ 和磁化面电流。")
w("")
w("**T6-2**：均匀磁化球（磁化强度 $M_0\\hat{\\boldsymbol{z}}$）的 $\\boldsymbol{B}$ 和 $\\boldsymbol{H}$ 分布。（提示：类比均匀极化介质球，$\\boldsymbol{H}_{\\text{in}}=-\\boldsymbol{M}/3$）")
w("")
w("**T6-3**（磁路定理）：环形铁芯（平均周长 $l$、截面积 $S$、$\\mu_r$、匝数 $N$）有一小气隙 $l_g$。求气隙中 $B$ 和线圈自感 $L$。")
w("")
w("**T6-4**：磁介质圆柱（半径 $a$，磁导率 $\\mu$）置于均匀外磁场 $\\boldsymbol{B}_0$ 中，$\\boldsymbol{B}_0\\perp$ 柱轴。证明柱内 $\\boldsymbol{B}_{\\text{in}}=\\frac{2\\mu}{\\mu+\\mu_0}B_0$。")
w("")

# ====== 第七章 ======
w("\\newpage")
w("# 第七章  电磁感应  ★★★（全卷最重要章节之一）")
w("")
w("> **对应课件**：EM007A–B（共223页）| **教材**：第7章 | **课时比重**：约18%")
w("")
w("## 核心考点")
w("")
w("### ★★★1. 法拉第电磁感应定律（必考核心）")
w("$$\\mathcal{E} = -\\frac{d\\Phi}{dt}, \\quad \\Phi = \\int_S \\boldsymbol{B}\\cdot d\\boldsymbol{S}$$")
w("**负号 = 楞次定律**：感应电流的磁通**反抗**原磁通的变化。")
w("注意：$\\Phi$ 的变化可来自 $B$ 变（感生）或面积/取向变（动生）或二者皆有。")
w("")
w("### ★★2. 动生电动势与感生电动势的区分")
w("")
w("| | 动生电动势 | 感生电动势 |")
w("|--|-----------|-----------|")
w("| 机制 | $\\boldsymbol{v}\\times\\boldsymbol{B}$（洛伦兹力） | $\\partial\\boldsymbol{B}/\\partial t$（涡旋电场） |")
w("| 公式 | $\\mathcal{E}=\\oint(\\boldsymbol{v}\\times\\boldsymbol{B})\\cdot d\\boldsymbol{l}$ | $\\mathcal{E}=-\\int_S\\frac{\\partial\\boldsymbol{B}}{\\partial t}\\cdot d\\boldsymbol{S}$ |")
w("| 非静电力 | 磁力分量 | 涡旋电场力 |")
w("")
w("### ★★★3. 涡旋电场（区分于静电场！）")
w("$$\\nabla\\times\\boldsymbol{E} = -\\frac{\\partial\\boldsymbol{B}}{\\partial t} \\neq 0$$")
w("涡旋电场**不是保守场**！$\\oint\\boldsymbol{E}\\cdot d\\boldsymbol{l} \\neq 0$，不能定义标量势。")
w("**经典考题**：长直螺线管内 $B$ 变化→管内 $E\\propto r$，管外 $E\\propto 1/r$。")
w("")
w("### ★★4. 互感和自感")
w("$$\\mathcal{E}_2 = -M\\frac{dI_1}{dt}, \\quad \\mathcal{E}_L = -L\\frac{dI}{dt}$$")
w("$M_{12}=M_{21}$（互感的对称性—纽曼公式）。$L>0$ 恒成立。")
w("串联：顺串 $L=L_1+L_2+2M$，反串 $L=L_1+L_2-2M$。")
w("")
w("### ★★5. 暂态过程（▲计算题高频考点）")
w("")
w("| 电路 | 方程 | 解 | $\\tau$ |")
w("|------|------|-----|--------|")
w("| RL（充） | $L\\dot{I}+RI=\\mathcal{E}$ | $I=I_0(1-e^{-t/\\tau})$ | $L/R$ |")
w("| RL（放） | $L\\dot{I}+RI=0$ | $I=I_0 e^{-t/\\tau}$ | $L/R$ |")
w("| RC（充） | $R\\dot{q}+q/C=\\mathcal{E}$ | $q=Q_0(1-e^{-t/\\tau})$ | $RC$ |")
w("| RC（放） | $R\\dot{q}+q/C=0$ | $q=Q_0 e^{-t/\\tau}$ | $RC$ |")
w("| RLC 串联 | $L\\ddot{q}+R\\dot{q}+q/C=0$ | 三态（欠/临界/过阻尼） | $\\omega_0=1/\\sqrt{LC}$ |")
w("")
w("※ **关键**：临界阻尼条件 $R=2\\sqrt{L/C}$，欠阻尼振荡频率 $\\omega_1=\\sqrt{\\omega_0^2-(R/2L)^2}$。")
w("")
w("## ▲ 自测习题（7题）")
w("")
w("**T7-1**（动生）：导体棒长 $l$，在 $B$ 中以角速度 $\\omega$ 绕一端旋转（$B\\perp$ 转面），求棒两端电动势。")
w("")
w("**T7-2**（感生/涡旋电场）：长螺线管（半径 $R$，$n$ 匝/m）$dI/dt=k$。求管内外的涡旋电场 $E(r)$。若在管外放一导体棒，求棒两端电动势。")
w("")
w("**T7-3**（互感+感应）：两同心共面圆线圈（$a\\ll b$），大线圈通 $I=I_0\\sin\\omega t$。求小线圈中感应电流，以及大线圈对小线圈的平均力矩。")
w("")
w("**T7-4**（自感计算）：同轴电缆（内实心圆柱半径 $a$，外薄壳半径 $b$）单位长自感。分别用磁通法和磁能法。")
w("")
w("**T7-5**（RL暂态）：$L=0.5\\,\\text{H}$，$R=10\\,\\Omega$，$\\mathcal{E}=12\\,\\text{V}$。求 $I(t)$、$\\tau$、$t=3\\tau$ 时的电流，以及电感中最终储能。")
w("")
w("**T7-6**（RLC暂态）：$L=0.1\\,\\text{H}$，$C=10\\,\\mu\\text{F}$。求临界阻尼的 $R$ 值；若 $R=50\\,\\Omega$ 判断振荡状态并求振荡频率。")
w("")
w("**T7-7**（能量守恒）：导体框架+滑棒在磁场中运动，从能量守恒角度分析动能→电能→焦耳热的转化。")
w("")

# ====== 第八章 ======
w("\\newpage")
w("# 第八章  磁能  ★★")
w("")
w("> **对应课件**：EM007B后半部分 | **教材**：第8章 | **课时比重**：约5%")
w("")
w("## 核心考点")
w("")
w("### ★1. 磁能与磁能密度")
w("$$W_m = \\frac{1}{2}LI^2 = \\frac{1}{2}\\sum_i L_i I_i^2 + \\frac{1}{2}\\sum_{i\\neq j}M_{ij}I_i I_j$$")
w("$$w_m = \\frac{1}{2}\\boldsymbol{B}\\cdot\\boldsymbol{H} = \\frac{B^2}{2\\mu_0\\mu_r}$$")
w("")
w("### ★★2. 虚功原理求磁力（类比静电力）")
w("| 条件 | 公式 |")
w("|------|------|")
w("| 磁链不变 $\\Psi$=const | $F = -\\partial W_m/\\partial x\\|_\\Psi$ |")
w("| 电流不变 $I$=const | $F = +\\partial W_m/\\partial x\\|_I$ |")
w("")
w("### 3. 磁能法求自感")
w("$$L = \\frac{2W_m}{I^2}$$")
w("当磁通匝链计算困难时（如粗导线），磁能法更优越。")
w("")
w("## ▲ 自测习题（3题）")
w("")
w("**T8-1**：用磁能法求同轴电缆单位长自感。比较空心内导体和实心内导体的结果差异。")
w("")
w("**T8-2**：两平行无限长载流导线（间距 $d$），用虚功原理求单位长作用力。")
w("")
w("**T8-3**：电磁铁衔铁受力公式 $F = B^2 S/(2\\mu_0)$ 的推导和应用。")
w("")

# ====== 第九章 ======
w("\\newpage")
w("# 第九章  交流电路  ★★")
w("")
w("> **对应课件**：EM007B后半部分 | **教材**：第9章 | **课时比重**：约7%")
w("")
w("## 核心考点")
w("")
w("### ★★1. 复数法（核心工具）")
w("$$\\tilde{U} = U_m e^{j(\\omega t+\\varphi_u)}, \\quad \\dot{U} = \\frac{U_m}{\\sqrt{2}}e^{j\\varphi_u}$$")
w("$$Z_R = R, \\quad Z_L = j\\omega L, \\quad Z_C = \\frac{1}{j\\omega C} = -\\frac{j}{\\omega C}$$")
w("欧姆定律复数形式：$\\dot{U} = Z\\dot{I}$。串联：$Z=\\sum Z_i$；并联：$1/Z = \\sum 1/Z_i$。")
w("")
w("### ★★2. 交流电功率")
w("$$P = UI\\cos\\varphi \\quad \\text{（有功功率=平均功率）}$$")
w("$$\\cos\\varphi = \\frac{R}{|Z|} \\quad \\text{（功率因数）}$$")
w("$S=UI$（视在功率），$Q=UI\\sin\\varphi$（无功功率）。")
w("")
w("### ★★3. RLC谐振（高频考点）")
w("$$\\omega_0 = \\frac{1}{\\sqrt{LC}}, \\quad f_0 = \\frac{1}{2\\pi\\sqrt{LC}}$$")
w("$$Q = \\frac{\\omega_0 L}{R} = \\frac{1}{\\omega_0 CR} = \\frac{1}{R}\\sqrt{\\frac{L}{C}}$$")
w("谐振时：$Z=R$（最小，纯阻性），$I$ 最大，$\\cos\\varphi=1$。")
w("$U_L = U_C = QU$（可远大于电源电压！$Q$ 越大越显著）。")
w("通频带：$\\Delta\\omega = \\omega_0/Q = R/L$。")
w("")
w("## ▲ 自测习题（4题）")
w("")
w("**T9-1**：RLC串联电路 $R=20\\Omega$，$L=0.1\\text{H}$，$C=5\\mu\\text{F}$，接 $U=220\\text{V},50\\text{Hz}$。求 $I$、$\\cos\\varphi$、各元件电压。")
w("")
w("**T9-2**：求上题谐振频率，并计算谐振时的 $I$、$U_L$、$U_C$ 和 $Q$ 值。")
w("")
w("**T9-3**：设计一串谐电路，$f_0=1\\text{MHz}$，$Q=100$，$C=100\\text{pF}$。求 $L$ 和 $R$。")
w("")
w("**T9-4**：变压器原边 $N_1=1000$，副边 $N_2=100$，原边接 $220\\text{V}$。求副边开路电压。若副边负载 $10\\Omega$，反射到原边的等效电阻多大？")
w("")

# ====== 第十章 ======
w("\\newpage")
w("# 第十章  麦克斯韦电磁理论  ★★★")
w("")
w("> **对应课件**：EM010A–C（共208页）| **教材**：第10章 | **课时比重**：约12%")
w("")
w("## 核心考点")
w("")
w("### ★★★1. 位移电流（麦克斯韦的核心贡献）")
w("$$\\boldsymbol{j}_D = \\frac{\\partial\\boldsymbol{D}}{\\partial t}$$")
w("**物理意义**：变化的电场也激发磁场——这是电磁波存在的理论基础。")
w("典型考题：平行板电容器充/放电时，极板间的 $\\boldsymbol{j}_D$ 和磁场的计算。")
w("")
w("### ★★★2. 麦克斯韦方程组（必考！必须能默写）")
w("")
w("**真空中（积分形式）**：")
w("$$\\oint_S \\boldsymbol{E}\\cdot d\\boldsymbol{S} = \\frac{Q}{\\varepsilon_0} \\qquad \\text{(1) 高斯定理}$$")
w("$$\\oint_S \\boldsymbol{B}\\cdot d\\boldsymbol{S} = 0 \\qquad \\text{(2) 磁通连续}$$")
w("$$\\oint_L \\boldsymbol{E}\\cdot d\\boldsymbol{l} = -\\int_S\\frac{\\partial\\boldsymbol{B}}{\\partial t}\\cdot d\\boldsymbol{S} \\qquad \\text{(3) 法拉第定律}$$")
w("$$\\oint_L \\boldsymbol{B}\\cdot d\\boldsymbol{l} = \\mu_0 I + \\mu_0\\varepsilon_0\\int_S\\frac{\\partial\\boldsymbol{E}}{\\partial t}\\cdot d\\boldsymbol{S} \\qquad \\text{(4) 安培-麦克斯韦}$$")
w("")
w("**微分形式**（也要能写）：")
w("$$\\nabla\\cdot\\boldsymbol{E} = \\frac{\\rho}{\\varepsilon_0}, \\quad \\nabla\\cdot\\boldsymbol{B} = 0$$")
w("$$\\nabla\\times\\boldsymbol{E} = -\\frac{\\partial\\boldsymbol{B}}{\\partial t}, \\quad \\nabla\\times\\boldsymbol{B} = \\mu_0\\boldsymbol{j} + \\mu_0\\varepsilon_0\\frac{\\partial\\boldsymbol{E}}{\\partial t}$$")
w("")
w("### ★★3. 平面电磁波")
w("由麦克斯韦方程组导出波动方程：$\\nabla^2\\boldsymbol{E} - \\frac{1}{c^2}\\frac{\\partial^2\\boldsymbol{E}}{\\partial t^2}=0$")
w("**平面波解** $\\boldsymbol{E}=\\boldsymbol{E}_0 e^{i(\\boldsymbol{k}\\cdot\\boldsymbol{r}-\\omega t)}$ 的性质：")
w("- $\\boldsymbol{k}\\perp\\boldsymbol{E}\\perp\\boldsymbol{B}$（横波），$\\boldsymbol{E}\\perp\\boldsymbol{B}$")
w("- $E_0 = c B_0$（真空中），$\\omega = ck$")
w("- 相速度 $v = c/\\sqrt{\\mu_r\\varepsilon_r}$，折射率 $n = \\sqrt{\\mu_r\\varepsilon_r}$")
w("")
w("### ★★4. 坡印亭定理与坡印亭矢量（能量守恒）")
w("$$\\boldsymbol{S} = \\boldsymbol{E}\\times\\boldsymbol{H} \\quad \\text{（能流密度，W/m}^2\\text{）}$$")
w("$$\\frac{\\partial w}{\\partial t} + \\nabla\\cdot\\boldsymbol{S} = -\\boldsymbol{j}\\cdot\\boldsymbol{E}$$")
w("$$w = \\frac{1}{2}(\\boldsymbol{E}\\cdot\\boldsymbol{D} + \\boldsymbol{B}\\cdot\\boldsymbol{H}) \\quad \\text{（电磁场能量密度）}$$")
w("")
w("### 5. 电磁动量与辐射压力")
w("$$\\boldsymbol{g} = \\frac{\\boldsymbol{S}}{c^2} = \\varepsilon_0(\\boldsymbol{E}\\times\\boldsymbol{B})$$")
w("辐射压力：全吸收 $p=I/c$，全反射 $p=2I/c$。")
w("")
w("## ▲ 自测习题（6题）")
w("")
w("**T10-1**（位移电流）：平行板电容器（圆极板半径 $a$），$U=U_0\\sin\\omega t$。求位移电流密度和极板间 $B(r)$。")
w("")
w("**T10-2**（麦克斯韦方程组的完备性）：说明为什么必须引入位移电流项。如果没有位移电流，安培环路定理会导致什么矛盾？（以电容器充放电为例）")
w("")
w("**T10-3**（波动方程推导）：从麦克斯韦方程组出发，推导真空中 $\\boldsymbol{E}$ 和 $\\boldsymbol{B}$ 的波动方程。")
w("")
w("**T10-4**（平面波性质）：真空中平面电磁波 $E_x=E_0\\cos(kz-\\omega t)$，求 $\\boldsymbol{B}$ 表达式、$\\langle S\\rangle$、$\\langle w\\rangle$。")
w("")
w("**T10-5**（坡印亭矢量）：载流长直导线表面 $E$ 沿轴向、$B$ 沿环向。求表面 $\\boldsymbol{S}$ 的方向和大小，说明能量从空间流入导线。")
w("")
w("**T10-6**（辐射压力）：激光功率 $P=3\\,\\text{mW}$，光斑直径 $2\\,\\text{mm}$，屏幕反射率 $70\\%$。求屏幕受到的光压。")
w("")

# ====== 综合 ======
w("\\newpage")
w("# 综合模拟题")
w("")
w("**M1（场与介质综合）**：半径为 $a$ 的导体球带电荷 $Q$，外有同心介质球壳（$a<r<b$，$\\varepsilon_r$），球壳外为真空。")
w("(1) 求全空间 $\\boldsymbol{D},\\boldsymbol{E},\\boldsymbol{P}$；(2) 介质壳内外表面的极化电荷；(3) 导体球电势和系统电容。")
w("")
w("**M2（磁与感应综合）**：半径为 $a$ 的圆柱形永磁体（沿轴均匀磁化 $\\boldsymbol{M}_0$），在外围同轴绕有 $N$ 匝线圈（半径 $b>a$）。")
w("(1) 求永磁体轴线上 $B$；(2) 线圈与永磁体间的互感；(3) 若线圈通有交变电流，永磁体是否会退磁？分析能量关系。")
w("")
w("**M3（暂态+能量综合）**：$RLC$ 串联电路，$L=0.2\\,\\text{H}$，$C=5\\,\\mu\\text{F}$，$R=20\\,\\Omega$，电容初始电压 $U_0=100\\,\\text{V}$。")
w("(1) 判断振荡状态；(2) 写出 $q(t)$ 表达式；(3) 求第一个半周期内电阻消耗的能量和电路中剩余的总电磁能。")
w("")
w("**M4（电磁波+能量综合）**：太阳常数 $S_0=1.36\\times 10^3\\,\\text{W/m}^2$。")
w("(1) 求太阳光中 $E_0$ 和 $B_0$；(2) 太阳光对地球的辐射压力（假设全吸收）；(3) 若一太阳能电池板效率 $20\\%$，面积 $1\\,\\text{m}^2$，求输出电功率。")
w("")
w("**M5（对称性+方法综合）**：比较并总结静电学中的 $\\boldsymbol{D}$ 与静磁学中的 $\\boldsymbol{H}$ 在引入动机、基本方程、边界条件和计算方法上的完全对称性。指出二者的根本不同之处（磁单极子不存在）。")
w("")

# ====== 附录 ======
w("\\newpage")
w("# 附录A：电场与磁场的完全对称性对比")
w("")
w("| 静电学量 | 静磁学量 | 对称关系 |")
w("|---------|---------|---------|")
w("| $\\boldsymbol{E}$（电场强度） | $\\boldsymbol{B}$（磁感应强度） | 基本场量 |")
w("| $\\boldsymbol{D}=\\varepsilon_0\\boldsymbol{E}+\\boldsymbol{P}$ | $\\boldsymbol{H}=\\boldsymbol{B}/\\mu_0-\\boldsymbol{M}$ | 辅助场量（注意符号差异！）|")
w("| $\\boldsymbol{P}$（极化强度） | $\\boldsymbol{M}$（磁化强度） | 介质响应 |")
w("| $\\oint\\boldsymbol{D}\\cdot d\\boldsymbol{S}=Q_f$ | $\\oint\\boldsymbol{H}\\cdot d\\boldsymbol{l}=I_f$ | 仅与自由源有关 |")
w("| $\\oint\\boldsymbol{E}\\cdot d\\boldsymbol{l}=0$ | $\\oint\\boldsymbol{B}\\cdot d\\boldsymbol{S}=0$ | 保守性/无源性的体现 |")
w("| $C=Q/U$ | $L=\\Psi/I$ | 储能元件（$L\\leftrightarrow C$，$I\\leftrightarrow U$）|")
w("| $W_e=\\frac{1}{2}CU^2$ | $W_m=\\frac{1}{2}LI^2$ | 储能公式 |")
w("| $w_e=\\frac{1}{2}\\boldsymbol{D}\\cdot\\boldsymbol{E}$ | $w_m=\\frac{1}{2}\\boldsymbol{B}\\cdot\\boldsymbol{H}$ | 能量密度 |")
w("| $\\sigma'=\\boldsymbol{P}\\cdot\\hat{\\boldsymbol{n}}$ | $\\boldsymbol{i}'=\\boldsymbol{M}\\times\\hat{\\boldsymbol{n}}$ | 束缚源（注意叉积 vs. 点积！）|")
w("| $\\rho'=-\\nabla\\cdot\\boldsymbol{P}$ | $\\boldsymbol{j}'=\\nabla\\times\\boldsymbol{M}$ | 束缚体源（散度 vs. 旋度！）|")
w("| 磁荷不存在 ↔ $\\nabla\\cdot\\boldsymbol{B}=0$ | 自由电荷存在 ↔ $\\nabla\\cdot\\boldsymbol{D}=\\rho_f$ | **根本不对称性** |")
w("")
w("# 附录B：必背常数")
w("")
w("$$\\varepsilon_0 \\approx 8.85\\times 10^{-12}\\,\\text{F/m}, \\quad \\frac{1}{4\\pi\\varepsilon_0} \\approx 9\\times 10^9\\,\\text{N}\\cdot\\text{m}^2/\\text{C}^2$$")
w("$$\\mu_0 = 4\\pi\\times 10^{-7}\\,\\text{H/m} \\approx 1.26\\times 10^{-6}\\,\\text{H/m}$$")
w("$$c = \\frac{1}{\\sqrt{\\mu_0\\varepsilon_0}} \\approx 3\\times 10^8\\,\\text{m/s}$$")
w("$$e = 1.60\\times 10^{-19}\\,\\text{C}, \\quad m_e = 9.11\\times 10^{-31}\\,\\text{kg}$$")
w("")

# ====== 写入文件 ======
with open('d:/辰辰/first CC/final_review.md', 'w', encoding='utf-8') as f:
    f.write(content)

print(f"最终复习提纲已生成，共 {len(content.split(chr(10)))} 行")
