# -*- coding: utf-8 -*-
"""电磁学物理量——物理意义、记忆方法与使用指南"""

content = ""

def w(text):
    global content
    content += text + "\n"

# ====== 封面 ======
w("# 电磁学物理量理解与记忆指南")
w("")
w("> **「物理不是背出来的，是理解出来的。但理解之后，需要好的记忆框架来快速调用。」**")
w("")
w("> 本指南按**\"场 → 源 → 介质响应 → 能量\"**的逻辑链组织，")
w("> 利用电场与磁场的**完全对称性**作为核心记忆框架。")
w("")

# ================================================================
# 总览
# ================================================================
w("\\newpage")
w("# 第一部分：全局框架——电场与磁场的\"对称性语言\"")
w("")
w("电磁学看似公式繁多，但本质上是**同一套数学结构讲了两个对称的故事**。")
w("一旦掌握这个对称性，你需要记忆的公式直接减半。")
w("")
w("## 核心对称表（最重要的一页！）")
w("")
w("| 概念 | 电场世界 | 磁场世界 | 对称性说明 |")
w("|------|---------|---------|-----------|")
w("| **源** | 电荷 $q,\\rho$（有单极子） | （无磁单极子） | **根本不对称** |")
w("| **基本场量** | $\\boldsymbol{E}$ [N/C 或 V/m] | $\\boldsymbol{B}$ [T 或 N/(A·m)] | 直接定义力 |")
w("| **辅助场量** | $\\boldsymbol{D}$ [C/m²] | $\\boldsymbol{H}$ [A/m] | 简化介质问题 |")
w("| **介质响应量** | $\\boldsymbol{P}$ [C/m²] | $\\boldsymbol{M}$ [A/m] | 单位体积偶极矩 |")
w("| **本构关系** | $\\boldsymbol{D}=\\varepsilon_0\\boldsymbol{E}+\\boldsymbol{P}$ | $\\boldsymbol{H}=\\boldsymbol{B}/\\mu_0-\\boldsymbol{M}$ | **注意±号不同！** |")
w("| **线性介质** | $\\boldsymbol{D}=\\varepsilon_0\\varepsilon_r\\boldsymbol{E}$ | $\\boldsymbol{B}=\\mu_0\\mu_r\\boldsymbol{H}$ | $\\varepsilon_r\\leftrightarrow\\mu_r$ |")
w("| **通量定理** | $\\oint\\boldsymbol{D}\\cdot d\\boldsymbol{S}=Q_f$ | $\\oint\\boldsymbol{B}\\cdot d\\boldsymbol{S}=0$ | 有源 ↔ 无源 |")
w("| **环量定理(静)** | $\\oint\\boldsymbol{E}\\cdot d\\boldsymbol{l}=0$ | $\\oint\\boldsymbol{H}\\cdot d\\boldsymbol{l}=I_f$ | 无旋 ↔ 有旋 |")
w("| **储能元件** | 电容 $C$ [F] | 电感 $L$ [H] | $C\\leftrightarrow L$ |")
w("| **储能公式** | $W_e=\\frac{1}{2}CU^2$ | $W_m=\\frac{1}{2}LI^2$ | $U\\leftrightarrow I$ |")
w("| **能量密度** | $w_e=\\frac{1}{2}\\boldsymbol{D}\\cdot\\boldsymbol{E}$ | $w_m=\\frac{1}{2}\\boldsymbol{B}\\cdot\\boldsymbol{H}$ | 形式完全相同 |")
w("| **束缚面源** | $\\sigma'=\\boldsymbol{P}\\cdot\\hat{\\boldsymbol{n}}$ | $\\boldsymbol{i}'=\\boldsymbol{M}\\times\\hat{\\boldsymbol{n}}$ | **点积↔叉积！** |")
w("| **束缚体源** | $\\rho'=-\\nabla\\cdot\\boldsymbol{P}$ | $\\boldsymbol{j}'=\\nabla\\times\\boldsymbol{M}$ | **散度↔旋度！** |")
w("")
w("## 为什么不完全对称？")
w("")
w("根本原因只有一个：**自然界存在独立的电荷（电单极子），但不存在独立的磁荷（磁单极子）**。")
w("这导致：")
w("- $\\nabla\\cdot\\boldsymbol{D}=\\rho_f$（电场有源），$\\nabla\\cdot\\boldsymbol{B}=0$（磁场无源）")
w("- $\\boldsymbol{P}$ 的源是标量 $\\rho'=-\\nabla\\cdot\\boldsymbol{P}$；$\\boldsymbol{M}$ 的源是矢量 $\\boldsymbol{j}'=\\nabla\\times\\boldsymbol{M}$")
w("- $D$ 线起止于自由电荷；$B$ 线永远是闭合曲线")
w("")

# ================================================================
# 电场世界
# ================================================================
w("\\newpage")
w("# 第二部分：电场世界——各物理量的物理意义")
w("")
w("## 「源头」——电荷 $q$、$\\rho$、$\\sigma$、$\\lambda$")
w("")
w("| 符号 | 名称 | 单位 | 物理图像 |")
w("|------|------|------|---------|")
w("| $q$ | 点电荷 | C（库仑） | 电的\"原子\"——最小的独立源 |")
w("| $\\rho$ | 体电荷密度 | C/m³ | 三维空间中电荷的\"浓度\" |")
w("| $\\sigma$ | 面电荷密度 | C/m² | 导体表面的电荷\"面密度\" |")
w("| $\\lambda$ | 线电荷密度 | C/m | 细导线上的电荷\"线密度\" |")
w("")
w("**记忆要点**：电荷是电场的**唯一来源**。一切电场问题都从\"电荷在哪里？\"开始。")
w("")
w("## 「力的传递者」——电场强度 $\\boldsymbol{E}$")
w("")
w("### 物理意义（最重要！）")
w("")
w("$$\\boldsymbol{E} = \\frac{\\boldsymbol{F}}{q_0}$$")
w("")
w("**$\\boldsymbol{E}$ 是单位正电荷所受的力。** 这是它的定义，也是理解一切电场问题的出发点。")
w("")
w("- 如果在空间某点放一个很小的正试探电荷 $q_0$，它受到的力除以 $q_0$ 就是该点的 $\\boldsymbol{E}$")
w("- $\\boldsymbol{E}$ 是矢量场：空间中每一点都有一个方向和大小")
w("- **静电场**中 $\\oint\\boldsymbol{E}\\cdot d\\boldsymbol{l}=0$——沿任意闭合回路走一圈，$\\boldsymbol{E}$ 做的总功为零（保守场）")
w("- **非静电场**（涡旋电场）中 $\\oint\\boldsymbol{E}\\cdot d\\boldsymbol{l} \\neq 0$——由变化的磁场产生")
w("")
w("### 量纲记忆")
w("$[E] = \\text{N/C} = \\text{V/m}$。N/C 来自定义；V/m 来自 $E=-\\nabla\\varphi$。两者等价。")
w("")
w("## 「标量化的 $\\boldsymbol{E}$」——电势 $\\varphi$")
w("")
w("$$\\varphi(\\boldsymbol{r}) = \\int_{\\boldsymbol{r}}^{\\infty} \\boldsymbol{E}\\cdot d\\boldsymbol{l}$$")
w("")
w("- **物理意义**：把单位正电荷从 $\\boldsymbol{r}$ 移到无穷远，电场力做的功")
w("- **为什么引入 $\\varphi$？** $\\varphi$ 是标量，处理起来比矢量 $\\boldsymbol{E}$ 简单。先求 $\\varphi$，再用 $\\boldsymbol{E}=-\\nabla\\varphi$ 得电场")
w("- **电压** = 电势差：$U_{ab} = \\varphi_a - \\varphi_b$")
w("- **等势面**：$\\varphi$ 相等的面，$\\boldsymbol{E}$ 永远垂直于等势面")
w("")
w("**记忆图像**：电势就像\"高度\"——电荷在电场中\"往下滑\"（从高电势到低电势）。$\\boldsymbol{E}$ 指向\"最陡的下坡方向\"。")
w("")
w("## 「介质中的帮手」——电位移矢量 $\\boldsymbol{D}$")
w("")
w("### 为什么要引入 $\\boldsymbol{D}$？")
w("")
w("在介质中，除了自由电荷 $Q_f$，还有极化电荷 $Q'$。高斯定理本应是：")
w("$$\\oint \\boldsymbol{E}\\cdot d\\boldsymbol{S} = \\frac{Q_f + Q'}{\\varepsilon_0}$$")
w("但 $Q'$ 通常未知——这就是引入 $\\boldsymbol{D}$ 的动机：**$\\boldsymbol{D}$ 的通量只与自由电荷有关**。")
w("$$\\oint \\boldsymbol{D}\\cdot d\\boldsymbol{S} = Q_f$$")
w("**这大大简化了对称性好的介质问题：先用自由电荷分布求 $\\boldsymbol{D}$，再通过本构关系求 $\\boldsymbol{E}$。**")
w("")
w("### 定义")
w("$$\\boldsymbol{D} = \\varepsilon_0\\boldsymbol{E} + \\boldsymbol{P}$$")
w("- $\\varepsilon_0\\boldsymbol{E}$：真空中的电场贡献")
w("- $\\boldsymbol{P}$：介质极化对 $\\boldsymbol{D}$ 的额外贡献")
w("- 在各向同性线性介质中：$\\boldsymbol{D} = \\varepsilon_0\\varepsilon_r\\boldsymbol{E}$（$\\boldsymbol{D}\\parallel\\boldsymbol{E}$，方向相同！）")
w("")
w("### 与 $\\boldsymbol{E}$ 的对比")
w("| | $\\boldsymbol{E}$ | $\\boldsymbol{D}$ |")
w("|--|-----------|-----------|")
w("| 通量源 | 所有电荷（自由+极化） | **仅自由电荷** |")
w("| 边界条件 | $E_t$ 连续 | $D_n$ 连续（无自由面电荷时） |")
w("| 在介质界面上 | 一般不连续 | 法向连续 |")
w("")
w("## 「介质对电场的反应」——极化强度 $\\boldsymbol{P}$")
w("")
w("$$\\boldsymbol{P} = \\frac{\\sum_i \\boldsymbol{p}_i}{\\Delta V}$$")
w("")
w("- **物理图像**：外电场使介质分子中的正负电荷中心分离→形成电偶极子→$\\boldsymbol{P}$ 是单位体积内的总电偶极矩")
w("- **$\\boldsymbol{P}$ 产生的电荷**：体 $\\rho'=-\\nabla\\cdot\\boldsymbol{P}$（$\\boldsymbol{P}$ 不均匀处有体极化电荷）、面 $\\sigma'=\\boldsymbol{P}\\cdot\\hat{\\boldsymbol{n}}$（表面有面极化电荷）")
w("- **线性介质中**：$\\boldsymbol{P} = \\chi_e\\varepsilon_0\\boldsymbol{E}$（$\\boldsymbol{P}\\parallel\\boldsymbol{E}$）")
w("- **$\\chi_e$（电极化率）** 反映介质容易被极化的程度。$\\chi_e>0$，$\\varepsilon_r=1+\\chi_e>1$")
w("")

# ================================================================
# 磁场世界
# ================================================================
w("\\newpage")
w("# 第三部分：磁场世界——各物理量的物理意义")
w("")
w("## 「源头」——电流 $I$、$\\boldsymbol{j}$、$\\boldsymbol{K}$")
w("")
w("| 符号 | 名称 | 单位 | 物理图像 |")
w("|------|------|------|---------|")
w("| $I$ | 电流强度 | A（安培） | 单位时间通过截面的电荷量 |")
w("| $\\boldsymbol{j}$ | 电流密度 | A/m² | 电流的\"矢量版\"——每点的流动方向和强度 |")
w("| $\\boldsymbol{K}$ | 面电流密度 | A/m | 薄导体表面的电流（如导体壳表面） |")
w("")
w("**$I = \\int_S \\boldsymbol{j}\\cdot d\\boldsymbol{S}$**：电流是电流密度穿过某个截面的\"总通量\"。")
w("")
w("**记忆要点**：电流是磁场的**唯一来源**（不考虑位移电流时）。一切静磁场问题都从\"电流在哪里？\"开始。这与\"电荷是电场的唯一来源\"完全对称。")
w("")
w("## 「力的传递者」——磁感应强度 $\\boldsymbol{B}$")
w("")
w("### 物理意义（最重要！）")
w("")
w("$$\\boldsymbol{F} = q\\boldsymbol{v}\\times\\boldsymbol{B} \\quad \\text{（洛伦兹磁力）}$$")
w("")
w("**$\\boldsymbol{B}$ 决定了运动电荷在磁场中受力的大小和方向。**")
w("")
w("- **$\\boldsymbol{B}$ 不作用在静止电荷上！** 这是电场和磁场的关键区别")
w("- 力 $\\perp \\boldsymbol{v}$ 且 $\\perp \\boldsymbol{B}$：磁力永远不做功（它只改变运动方向，不改变速率）")
w("- $\\boldsymbol{B}$ 的方向 = 小磁针 N 极的指向（历史上最早的定义）")
w("- **$\\nabla\\cdot\\boldsymbol{B}=0$**：$B$ 线永远是闭合的（无起点、无终点），这直接源于不存在磁单极子")
w("")
w("### 量纲记忆")
w("$[B] = \\text{T} = \\text{N}/(\\text{A}\\cdot\\text{m})$。1T 是很大的磁场——地球磁场只有约 $0.5\\times 10^{-4}$T。")
w("")
w("## 「介质中的帮手」——磁场强度 $\\boldsymbol{H}$")
w("")
w("### 为什么要引入 $\\boldsymbol{H}$？")
w("")
w("与 $\\boldsymbol{D}$ 的引入动机完全对称：在磁介质中，安培环路定理本应是：")
w("$$\\oint \\boldsymbol{B}\\cdot d\\boldsymbol{l} = \\mu_0(I_f + I')$$")
w("其中 $I'$ 是磁化电流。引入 $\\boldsymbol{H}$ 后：")
w("$$\\oint \\boldsymbol{H}\\cdot d\\boldsymbol{l} = I_f$$")
w("**$\\boldsymbol{H}$ 的环量只与自由电流有关。**")
w("")
w("### 定义")
w("$$\\boldsymbol{H} = \\frac{\\boldsymbol{B}}{\\mu_0} - \\boldsymbol{M}$$")
w("")
w("**注意与 $\\boldsymbol{D}=\\varepsilon_0\\boldsymbol{E}+\\boldsymbol{P}$ 对比：一个是\"$+$\"，一个是\"$-$\"！这是最容易混淆的地方。**")
w("")
w("**记忆方法**：$\\boldsymbol{D}$ 的公式里 $\\boldsymbol{P}$ 前是 $+$，因为介质极化**增强**了 $\\boldsymbol{D}$（$\\varepsilon_r>1$）；$\\boldsymbol{H}$ 的公式里 $\\boldsymbol{M}$ 前是 $-$，因为磁化在定义 $\\boldsymbol{H}$ 时被\"减掉\"了。或者直接记线性关系：$\\boldsymbol{B}=\\mu_0\\mu_r\\boldsymbol{H}$ 和 $\\boldsymbol{D}=\\varepsilon_0\\varepsilon_r\\boldsymbol{E}$ 形式相同，无需记 $\\pm$。")
w("")
w("### 与 $\\boldsymbol{B}$ 的对比")
w("| | $\\boldsymbol{B}$ | $\\boldsymbol{H}$ |")
w("|--|-----------|-----------|")
w("| 通量特性 | $\\oint\\boldsymbol{B}\\cdot d\\boldsymbol{S}=0$（无条件） | （无对应定理） |")
w("| 环量特性 | （含磁化电流） | $\\oint\\boldsymbol{H}\\cdot d\\boldsymbol{l}=I_f$（仅自由电流） |")
w("| 边界条件 | $B_n$ 连续（无磁荷） | $H_t$ 连续（无面自由电流时） |")
w("| 在线性介质中 | $\\boldsymbol{B}=\\mu_0\\mu_r\\boldsymbol{H}$ | — |")
w("")
w("## 「介质对磁场的反应」——磁化强度 $\\boldsymbol{M}$")
w("")
w("$$\\boldsymbol{M} = \\frac{\\sum_i \\boldsymbol{m}_i}{\\Delta V}$$")
w("")
w("- **物理图像**：外磁场使分子磁矩趋向排列→$\\boldsymbol{M}$ 是单位体积内的总磁矩")
w("- **$\\boldsymbol{M}$ 产生的电流**：体 $\\boldsymbol{j}'=\\nabla\\times\\boldsymbol{M}$（$\\boldsymbol{M}$ 不均匀处有体磁化电流）、面 $\\boldsymbol{i}'=\\boldsymbol{M}\\times\\hat{\\boldsymbol{n}}$（表面有面磁化电流）")
w("- 注意与 $\\boldsymbol{P}$ 对比：$\\rho'=-\\nabla\\cdot\\boldsymbol{P}$（散度）→ $\\boldsymbol{j}'=\\nabla\\times\\boldsymbol{M}$（旋度）。因为电荷是标量，电流是矢量。")
w("- **线性介质中**：$\\boldsymbol{M}=\\chi_m\\boldsymbol{H}$（顺磁质 $\\chi_m>0$；抗磁质 $\\chi_m<0$）。$\\mu_r=1+\\chi_m$")
w("")
w("## 「磁场的矢量势」——磁矢势 $\\boldsymbol{A}$")
w("")
w("$$\\boldsymbol{B} = \\nabla\\times\\boldsymbol{A}, \\quad \\nabla\\cdot\\boldsymbol{A}=0 \\;\\text{（库仑规范）}$$")
w("")
w("- **为什么引入 $\\boldsymbol{A}$？** $\\boldsymbol{A}$ 是矢量但只有一个方程（$\\nabla^2\\boldsymbol{A}=-\\mu_0\\boldsymbol{j}$），比直接处理 $\\boldsymbol{B}$ 的毕奥-萨伐尔积分更系统")
w("- $\\boldsymbol{A}$ 的物理意义不如 $\\varphi$ 直观，但在量子力学（AB效应）和电磁辐射中至关重要")
w("- **规范不变性**：$\\boldsymbol{A}'=\\boldsymbol{A}+\\nabla\\chi$ 产生相同的 $\\boldsymbol{B}$——这对应了物理上的冗余自由度")
w("")

# ================================================================
# 跨世界物理量
# ================================================================
w("\\newpage")
w("# 第四部分：跨电场/磁场的通用物理量")
w("")
w("## 电容 $C$ 与电感 $L$（对偶量）")
w("")
w("| | 电容 $C$ | 电感 $L$ |")
w("|--|---------|---------|")
w("| 定义 | $C=Q/U$ | $L=\\Psi/I$ |")
w("| 物理意义 | 储存电荷/电场能的能力 | 储存磁通/磁场能的能力 |")
w("| **能量公式** | $W=\\frac{1}{2}CU^2=\\frac{Q^2}{2C}$ | $W=\\frac{1}{2}LI^2=\\frac{\\Psi^2}{2L}$ |")
w("| 串联 | $1/C=\\sum 1/C_i$ | $L=\\sum L_i$（无互感时） |")
w("| 并联 | $C=\\sum C_i$ | $1/L=\\sum 1/L_i$（无互感时） |")
w("| 单位 | F（法拉） | H（亨利） |")
w("| **电路中的作用** | 电压不能突变 | 电流不能突变 |")
w("| 交流阻抗 | $Z_C=1/(j\\omega C)$ | $Z_L=j\\omega L$ |")
w("")
w("**记忆公式的技巧**：$C$ 和 $L$ 是\"对偶\"量——把电容公式中的 $U\\leftrightarrow I$、串联$\\leftrightarrow$并联对调，就得到电感公式。")
w("")
w("## 电阻 $R$ 与电导 $G$")
w("")
w("- $R=U/I$（定义），$R = \\int\\frac{dl}{\\sigma S}$（计算）——阻碍电流流动")
w("- $G=1/R$（电导），$\\sigma=1/\\rho$（电导率）——衡量导电能力")
w("- **焦耳热**：$P=I^2R=U^2/R$——电能→热能的不可逆转化")
w("")
w("## 坡印亭矢量 $\\boldsymbol{S}$（能量\"流动\"的描述）")
w("")
w("$$\\boldsymbol{S} = \\boldsymbol{E}\\times\\boldsymbol{H} \\quad [\\text{W/m}^2]$$")
w("")
w("**物理意义**：$\\boldsymbol{S}$ 表示电磁场能量在空间中**流动的方向和强度**。")
w("")
w("**为什么重要？** 它颠覆了\"能量沿导线传输\"的直觉——实际上，能量是通过**导线周围的电磁场**从电源传到负载的，导线只是\"引导\"了能量流动的方向。")
w("")
w("**记忆方法**：$\\boldsymbol{S}=\\boldsymbol{E}\\times\\boldsymbol{H}$。右手定则：食指→$\\boldsymbol{E}$，中指→$\\boldsymbol{H}$，拇指→$\\boldsymbol{S}$（能量流动方向）。")
w("")
w("## 电磁动量密度 $\\boldsymbol{g}$")
w("")
w("$$\\boldsymbol{g} = \\frac{\\boldsymbol{S}}{c^2} = \\varepsilon_0(\\boldsymbol{E}\\times\\boldsymbol{B})$$")
w("")
w("**物理意义**：电磁场不仅携带能量，还携带动量。光照射物体表面产生压力（辐射压力）的根源在此。$p=I/c$（全吸收）或 $p=2I/c$（全反射）。")
w("")

# ================================================================
# 公式记忆法
# ================================================================
w("\\newpage")
w("# 第五部分：公式记忆的系统方法")
w("")
w("## 方法一：从\"源→场→力\"逻辑链推导")
w("")
w("**电场链**：电荷分布 $\\rho(\\boldsymbol{r})$ →（库仑定律+叠加）→ $\\boldsymbol{E}(\\boldsymbol{r})$ →（$\\boldsymbol{F}=q\\boldsymbol{E}$）→ 力")
w("")
w("**磁场链**：电流分布 $\\boldsymbol{j}(\\boldsymbol{r})$ →（毕奥-萨伐尔定律+叠加）→ $\\boldsymbol{B}(\\boldsymbol{r})$ →（$\\boldsymbol{F}=q\\boldsymbol{v}\\times\\boldsymbol{B}$）→ 力")
w("")
w("**记住这两个\"链\"，就能把孤立的公式串联起来。**")
w("")
w("## 方法二：利用对称性\"批量记忆\"")
w("")
w("1. **$C$ 的公式→$L$ 的公式**：同轴电缆 $C=\\frac{2\\pi\\varepsilon_0 l}{\\ln(b/a)}$ → $L=\\frac{\\mu_0 l}{2\\pi}\\ln\\frac{b}{a}$。注意 $\\varepsilon_0\\leftrightarrow\\mu_0$，位置对调（一个在分子，一个在分母前的系数中）。")
w("")
w("2. **平板电容→螺线管电感**：$C=\\varepsilon_0 S/d$ → $L=\\mu_0 n^2 Sl$。$S$（面积）、$l$（长度）、$\\varepsilon_0\\leftrightarrow\\mu_0$。")
w("")
w("3. **$D_n$ 连续 ↔ $B_n$ 连续**（法向边界条件）；**$E_t$ 连续 ↔ $H_t$ 连续**（切向边界条件，无自由源时）。")
w("")
w("## 方法三：从\"能量\"反推\"力\"和\"电路参数\"")
w("")
w("$$F = -\\frac{\\partial W}{\\partial x}$$")
w("")
w("只需记住能量表达式，力就自动得出。$C=2W_e/U^2$，$L=2W_m/I^2$——能量法求 $C$ 和 $L$ 比直接积分更普适。")
w("")
w("## 方法四：关键数值\"锚点\"")
w("")
w("| 常数 | 近似值 | 记忆技巧 |")
w("|------|--------|---------|")
w("| $\\frac{1}{4\\pi\\varepsilon_0}$ | $9\\times 10^9$ | \"库仑常数是9亿\"——$9\\times 10^9$ |")
w("| $\\varepsilon_0$ | $8.85\\times 10^{-12}$ | $\\approx 10^{-11}/36\\pi$（即 $1/(36\\pi\\times 10^9)$）|")
w("| $\\mu_0$ | $4\\pi\\times 10^{-7}$ | **精确值**（定义值），记住\"4π×10⁻⁷\" |")
w("| $c$ | $3\\times 10^8$ m/s | $c=1/\\sqrt{\\mu_0\\varepsilon_0}$——由 $\\mu_0,\\varepsilon_0$ 算出光速！ |")
w("| $e$ | $1.60\\times 10^{-19}$ C | \"一个电子带1.6×10⁻¹⁹库仑\" |")
w("| $m_e$ | $9.11\\times 10^{-31}$ kg | 电子质量极小 |")
w("")
w("**关键验证**：$1/\\sqrt{\\mu_0\\varepsilon_0} = 1/\\sqrt{(4\\pi\\times 10^{-7})(8.85\\times 10^{-12})} \\approx 3\\times 10^8$ m/s。这是麦克斯韦最伟大的发现之一——光速从电磁学常数推导出来！")
w("")

# ================================================================
# 常见混淆点
# ================================================================
w("\\newpage")
w("# 第六部分：最容易混淆的概念（避坑指南）")
w("")
w("## 1. $\\boldsymbol{E}$ vs. $\\boldsymbol{D}$（电场强度 vs. 电位移矢量）")
w("")
w("- **什么时候用 $\\boldsymbol{E}$？** 求电荷受力（$\\boldsymbol{F}=q\\boldsymbol{E}$）、求电势（$\\varphi=\\int\\boldsymbol{E}\\cdot d\\boldsymbol{l}$）、计算边界条件中的切向分量")
w("- **什么时候用 $\\boldsymbol{D}$？** 对称性好的介质问题中先用自由电荷+高斯定理求 $\\boldsymbol{D}$，再通过 $\\boldsymbol{D}=\\varepsilon_0\\varepsilon_r\\boldsymbol{E}$ 得 $\\boldsymbol{E}$")
w("- **常见错误**：在介质界面上认为 $E_n$ 连续——实际上连续的是 $D_n$（无自由面电荷时）！")
w("")
w("## 2. $\\boldsymbol{B}$ vs. $\\boldsymbol{H}$（磁感应强度 vs. 磁场强度）")
w("")
w("- **什么时候用 $\\boldsymbol{B}$？** 求运动电荷受力（$\\boldsymbol{F}=q\\boldsymbol{v}\\times\\boldsymbol{B}$）、求磁通量（$\\Phi=\\int\\boldsymbol{B}\\cdot d\\boldsymbol{S}$）、法拉第定律（$\\mathcal{E}=-d\\Phi/dt$）")
w("- **什么时候用 $\\boldsymbol{H}$？** 用安培环路定理求场（$\\oint\\boldsymbol{H}\\cdot d\\boldsymbol{l}=I_f$）、磁路定理中使用")
w("- **历史命名陷阱**：$\\boldsymbol{H}$ 叫\"磁场强度\"但 $\\boldsymbol{B}$ 才是决定力的基本场量！$\\boldsymbol{B}$ 的命名\"磁感应强度\"不如\"磁场强度\"直观——这是历史上命名的不幸。")
w("")
w("## 3. 静电场 vs. 涡旋电场")
w("")
w("| | 静电场 $\\boldsymbol{E}_s$ | 涡旋电场 $\\boldsymbol{E}_v$ |")
w("|--|-------------------|---------------------|")
w("| 产生原因 | 静止电荷 | 变化的磁场 $\\partial\\boldsymbol{B}/\\partial t$ |")
w("| $\\oint\\boldsymbol{E}\\cdot d\\boldsymbol{l}$ | $=0$（保守） | $\\neq 0$（非保守） |")
w("| 能否定义 $\\varphi$ | 能（$\\boldsymbol{E}=-\\nabla\\varphi$） | 不能！ |")
w("| 电力线形状 | 起于正电荷，止于负电荷 | 闭合曲线 |")
w("")
w("总电场 $\\boldsymbol{E}=\\boldsymbol{E}_s+\\boldsymbol{E}_v$。只有静电场部分对闭合回路积分为零。")
w("")
w("## 4. 极化电荷 vs. 自由电荷")
w("")
w("- **自由电荷**：可以宏观移动的电荷（导体中的电子、注入的电荷）。受 $\\boldsymbol{D}$ 的高斯定理控制。")
w("- **极化电荷（束缚电荷）**：介质分子极化产生的等效电荷，不能自由移动。$\\rho'=-\\nabla\\cdot\\boldsymbol{P}$。")
w("- **磁化电流 vs. 自由电流**（对称概念）：磁化电流 $\\boldsymbol{j}'=\\nabla\\times\\boldsymbol{M}$ 来自分子磁矩，不产生焦耳热。")
w("")
w("## 5. 动生电动势 vs. 感生电动势")
w("")
w("- **动生**：导体在磁场中运动→$\\boldsymbol{v}\\times\\boldsymbol{B}$ 力→$\\mathcal{E}=\\oint(\\boldsymbol{v}\\times\\boldsymbol{B})\\cdot d\\boldsymbol{l}$。非静电力 = 洛伦兹力。")
w("- **感生**：磁场随时间变化→涡旋电场→$\\mathcal{E}=-\\int\\frac{\\partial\\boldsymbol{B}}{\\partial t}\\cdot d\\boldsymbol{S}$。非静电力 = 涡旋电场力。")
w("- 两者在法拉第定律中**统一**为 $\\mathcal{E}=-d\\Phi/dt$，这是相对论协变性的体现。")
w("")

# ================================================================
# 快速自查
# ================================================================
w("\\newpage")
w("# 第七部分：考前快速自查清单")
w("")
w("考试前一晚，用这个清单逐项检查：")
w("")
w("## 必须能默写的公式（共12条）")
w("")
w("1. $\\oint\\boldsymbol{D}\\cdot d\\boldsymbol{S}=Q_f$ —— 电场高斯定理")
w("2. $\\oint\\boldsymbol{B}\\cdot d\\boldsymbol{S}=0$ —— 磁场高斯定理")
w("3. $\\oint\\boldsymbol{E}\\cdot d\\boldsymbol{l}=-\\int\\frac{\\partial\\boldsymbol{B}}{\\partial t}\\cdot d\\boldsymbol{S}$ —— 法拉第定律")
w("4. $\\oint\\boldsymbol{H}\\cdot d\\boldsymbol{l}=I_f+\\int\\frac{\\partial\\boldsymbol{D}}{\\partial t}\\cdot d\\boldsymbol{S}$ —— 安培-麦克斯韦定律")
w("5. $\\boldsymbol{D}=\\varepsilon_0\\boldsymbol{E}+\\boldsymbol{P}$，$\\boldsymbol{H}=\\boldsymbol{B}/\\mu_0-\\boldsymbol{M}$ —— 辅助场量定义")
w("6. $\\mathcal{E}=-d\\Phi/dt$ —— 法拉第定律（简化形式）")
w("7. $F=-\\partial W/\\partial x$ —— 虚功原理")
w("8. $w_e=\\frac{1}{2}\\boldsymbol{D}\\cdot\\boldsymbol{E}$，$w_m=\\frac{1}{2}\\boldsymbol{B}\\cdot\\boldsymbol{H}$ —— 能量密度")
w("9. $\\boldsymbol{S}=\\boldsymbol{E}\\times\\boldsymbol{H}$ —— 坡印亭矢量")
w("10. $c=1/\\sqrt{\\mu_0\\varepsilon_0}$ —— 真空中光速")
w("11. $\\omega_0=1/\\sqrt{LC}$ —— 谐振频率")
w("12. $\\tau=RC$（容性），$\\tau=L/R$（感性）—— 时间常数")
w("")
w("## 必须能推导的经典问题（共6类）")
w("")
w("1. 用高斯定理求球/柱/面对称电荷分布的 $\\boldsymbol{E}$")
w("2. 用安培环路定理求对称电流分布的 $\\boldsymbol{B}$")
w("3. 长直螺线管内 $B$ 变化→管内外的涡旋电场")
w("4. RL/RC 暂态过程的一阶微分方程求解")
w("5. 从麦克斯韦方程组导出电磁波波动方程")
w("6. RLC 串联谐振的阻抗分析和 $Q$ 值推导")
w("")
w("## 必须能解释的物理概念（共8个）")
w("")
w("1. 为什么引入 $\\boldsymbol{D}$ 和 $\\boldsymbol{H}$？（简化介质问题，通量/环量只与自由源有关）")
w("2. 位移电流的物理意义？（变化的电场也激发磁场——电磁波存在的理论基础）")
w("3. 楞次定律的\"负号\"意味着什么？（感应效果反抗引起感应的原因——能量守恒的体现）")
w("4. $B_n$ 连续 vs. $H_t$ 连续分别对应什么边界条件？")
w("5. 坡印亭矢量如何改变我们对\"能量沿导线传输\"的认知？")
w("6. 静电场和涡旋电场的本质区别是什么？")
w("7. 为什么均匀带电球面内部 $E=0$，而均匀带电球体内部 $E\\neq 0$？")
w("8. 为什么引入磁矢势 $\\boldsymbol{A}$？（规范理论的基础，$\\boldsymbol{B}=\\nabla\\times\\boldsymbol{A}$）")
w("")

# ====== 写入 ======
with open('d:/辰辰/first CC/physics_guide.md', 'w', encoding='utf-8') as f:
    f.write(content)

print(f"物理量理解记忆指南已生成，共 {len(content.split(chr(10)))} 行")
